// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpsDesk.Infrastructure.Persistence;

#nullable disable

namespace OpsDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpsDeskDbContext))]
    [Migration("20260916175701_RequireInvitationEmailDelivery")]
    partial class RequireInvitationEmailDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpsDesk.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("NewAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_assignee_id");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("PreviousAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_assignee_id");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_logs_occurred_id");

                    b.HasIndex("Action", "OccurredAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_audit_logs_action_occurred_id");

                    b.HasIndex("ActorId", "OccurredAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_audit_logs_actor_occurred_id");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_audit_logs_target_occurred_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_tokens_token_hash");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_verification_tokens_expiry", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_password_reset_tokens_expiry", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int>("ResolutionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_duration_minutes");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique()
                        .HasDatabaseName("ux_sla_policies_active_priority")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("sla_policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a12b536-55b3-48e3-a739-87f7614f3692"),
                            IsActive = true,
                            Priority = "Low",
                            ResolutionDurationMinutes = 10080
                        },
                        new
                        {
                            Id = new Guid("49eb7a75-aac7-483c-b932-c07de912f92c"),
                            IsActive = true,
                            Priority = "Medium",
                            ResolutionDurationMinutes = 5760
                        },
                        new
                        {
                            Id = new Guid("97c66820-ae7e-4575-8f9f-90b93522827c"),
                            IsActive = true,
                            Priority = "High",
                            ResolutionDurationMinutes = 2880
                        },
                        new
                        {
                            Id = new Guid("cd36040a-fd90-4e93-897c-b7854f05f20b"),
                            IsActive = true,
                            Priority = "Urgent",
                            ResolutionDurationMinutes = 1440
                        });
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<DateTime>("SlaDeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline_utc");

                    b.Property<Guid>("SlaPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_policy_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tickets_assignee_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_tickets_requester_id");

                    b.HasIndex("SlaDeadlineUtc")
                        .HasDatabaseName("ix_tickets_sla_deadline_utc");

                    b.HasIndex("SlaPolicyId")
                        .HasDatabaseName("ix_tickets_sla_policy_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketAssignmentChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("NewAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_assignee_id");

                    b.Property<Guid?>("PreviousAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_assignee_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("NewAssigneeId");

                    b.HasIndex("PreviousAssigneeId");

                    b.HasIndex("TicketId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_ticket_assignment_changes_ticket_created_id");

                    b.ToTable("ticket_assignment_changes", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_ticket_comments_ticket_created_id");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketSlaBreach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<DateTime>("SlaDeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline_utc");

                    b.Property<Guid>("SlaPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_policy_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("SlaPolicyId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ux_ticket_sla_breaches_ticket_id");

                    b.ToTable("ticket_sla_breaches", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_sla_breaches_detection_after_deadline", "detected_at_utc > sla_deadline_utc");
                        });
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("TicketId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_ticket_status_changes_ticket_created_id");

                    b.ToTable("ticket_status_changes", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("auth_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.UserExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_user_external_identities_issuer_subject");

                    b.ToTable("user_external_identities", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid?>("AcceptedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_sent_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_user_invitations_pending_email")
                        .HasFilter("revoked_at_utc IS NULL AND accepted_at_utc IS NULL");

                    b.HasIndex("InvitedById");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("user_invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_invitations_expiry", "expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_user_invitations_role", "role IN ('Customer', 'Agent')");
                        });
                });

            modelBuilder.Entity("OpsDesk.Infrastructure.Persistence.Entities.EmailVerificationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AvailableAtUtc", "Id");

                    b.ToTable("email_verification_jobs", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Infrastructure.Persistence.Entities.PasswordRecoveryJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AvailableAtUtc", "Id");

                    b.ToTable("password_recovery_jobs", (string)null);
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_actor");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("OpsDesk.Domain.Entities.EmailVerificationToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_user");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_assignee");

                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_requester");

                    b.HasOne("OpsDesk.Domain.Entities.SlaPolicy", null)
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_sla_policy");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketAssignmentChange", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignment_changes_actor");

                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("NewAssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_assignment_changes_new_assignee");

                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PreviousAssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_assignment_changes_previous_assignee");

                    b.HasOne("OpsDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignment_changes_ticket");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_author");

                    b.HasOne("OpsDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_ticket");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketSlaBreach", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.SlaPolicy", null)
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_sla_breaches_sla_policy");

                    b.HasOne("OpsDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_sla_breaches_ticket");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.TicketStatusChange", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_changes_actor");

                    b.HasOne("OpsDesk.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_changes_ticket");
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.UserExternalIdentity", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsDesk.Domain.Entities.UserInvitation", b =>
                {
                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsDesk.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
